name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt install gettext libncurses5-dev libpcre2-dev python3-pip
        sudo pip3 install pexpect
    - name: cmake
      env:
          # Some warnings upgraded to errors to match Open Build Service platforms
          CXXFLAGS: "-Werror=address -Werror=return-type"
      run: |
        mkdir build && cd build
        cmake ..
    - name: make
      run: |
        make
    - name: make test
      run: |
        make test

  ubuntu-32bit-vendored-pcre2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt install gettext lib32ncurses5-dev python3-pip g++-multilib
        sudo pip3 install pexpect
    - name: cmake
      env:
          CXXFLAGS: "-m32 -Werror=address -Werror=return-type"
          CFLAGS: "-m32"
      run: |
        mkdir build && cd build
        cmake ..
    - name: make
      run: |
        make
    - name: make test
      run: |
        make test


  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        brew install python3
        sudo pip3 install pexpect
    - name: cmake
      run: |
        mkdir build && cd build
        cmake -DWITH_GETTEXT=NO ..
    - name: make
      run: |
        make
    - name: make test
      run: |
        make test
